---
- name: Install logreduce if needed
  shell: |
    mkdir -p ~/.local/bin
    cd ~/.local
    # Small hack to enable using a local build
    if test -f /bin/logreduce; then
      ln -s /bin/logreduce bin
    else
      curl -L https://github.com/logreduce/logreduce/releases/download/v{{ logreduce_version }}/logreduce-x86_64-linux.tar.bz2 | tar xjvf -
    fi

- name: Set logreduce_cmd fact
  set_fact:
    logreduce_cmd: "{% if logreduce_debug %}env LOGREDUCE_LOG=debug {% endif %} {{ ansible_env.HOME }}/.local/bin/logreduce"
