---
- name: Install logreduce if needed
  shell: |
    mkdir -p ~/.local/
    cd ~/.local
    curl -L https://github.com/logreduce/logreduce/releases/download/v{{ logreduce_version }}/logreduce-x86_64-linux.tar.bz2 | tar xjvf -

- name: Set logreduce_cmd fact
  set_fact:
    logreduce_cmd: "{% if logreduce_debug %}env LOGREDUCE_LOG=debug {% endif %} {{ ansible_env.HOME }}/.local/bin/logreduce"
