---
- name: Detect anomalies
  ignore_errors: yes
  block:
    - include_tasks: install.yaml
    - include_tasks: run.yaml
  when:
    - not zuul_success | bool
    - logreduce_optin | default(False) | bool
