---
- name: Set model name
  set_fact:
    _model_name: "{{ zuul.project.name }}/{{ zuul.job }}/{{ zuul.branch }}{{ _model_hash }}.bin"

- name: Create directories
  file:
    path: "{{ item }}"
    mode: 0700
    state: directory
  with_items:
    - "{{ logreduce_tmp_dir }}"

- name: Download pre-built model
  get_url:
    url: "{{ logreduce_model_store_url }}/{{ _model_name }}"
    dest: "{{ _model_path }}"
  failed_when: false

- name: Copy config
  copy:
    content: "{{ logreduce_config | to_json }}"
    dest: "{{ logreduce_tmp_dir }}/logreduce-config.json"
  when: _has_config

- name: Check pre-built model
  shell: |
    {{ logreduce_cmd }} --model {{ _model_path }} check-model --max-age {{ logreduce_model_age }} || rm -f {{ _model_path }}
  register: _prebuilt_model_status

- name: Analyse the logs
  command: >
    timeout {{ logreduce_max_run_time }}s {{ logreduce_cmd }}
      --model {{ _model_path }}
      --report {{ zuul.executor.log_root }}/logreduce.bin
      {% if logreduce_web_url %}--web-package-url {{ logreduce_web_url }}{% endif %}
      {% if _has_config %}--config {{ logreduce_tmp_dir }}/logreduce-config.json {% endif %}
      zuul-build
      --api-url {{ logreduce_zuul_web }}
      {{ zuul.executor.log_root }}/
  register: _logreduce_run

- name: Copy built model
  when:
    - _logreduce_run.rc == 0
    - "'Good model' not in _prebuilt_model_status.stdout"
  block:
    - name: Move model to executor log
      command: "mv {{ _model_path }} {{ zuul.executor.log_root }}/model.bin"

    - name: Write model name
      copy:
        content: "{{ _model_name }}"
        dest: "{{ zuul.executor.log_root }}/model.name"

- name: Register the output
  when: _logreduce_run.rc == 0
  delegate_to: localhost
  zuul_return:
    data:
      zuul:
        artifacts:
          - name: "LogReduce report"
            url: "logreduce.html"
