---
- name: Install logjuicer if needed
  vars:
    local_cache: "/var/lib/log-classify/{{ logjuicer_version }}/logjuicer"
  shell: |
    mkdir -p ~/.local/bin
    cd ~/.local
    if test -f {{ local_cache }}; then
      ln -sf {{ local_cache }} ~/.local/bin
    else
      curl -L https://github.com/logjuicer/logjuicer/releases/download/{{ logjuicer_version }}/logjuicer-x86_64-linux.tar.bz2 | tar xjvf -
    fi

- name: Set logjuicer_cmd fact
  set_fact:
    logjuicer_cmd: "{% if logjuicer_debug %}env LOGJUICER_LOG=debug {% endif %} {{ ansible_env.HOME }}/.local/bin/logjuicer"
